#ifndef C2DUI_TEXT_DEF_H_
#define C2DUI_TEXT_DEF_H_

#if 0
// main framework
#define TEXT_NAVIGATION                                 "NAVIGATION"
#define TEXT_RUN                                        "RUN"
#define TEXT_TOOGLE_FAVORITE                            "ADD / REMOVE FAVORITE"
#define TEXT_FAVORITE                                   "FAVORITE"
#define TEXT_SWITCH_SYSTEM                              "SWITCH SYSTEM"
#define TEXT_MAIN_MENU                                  "MAIN MENU"
#define TEXT_ROM_MENU                                   "ROM MENU"

#define TEXT_ROMINFO_DELIMITER                          ": "
#define TEXT_ROMINFO_SYSTEM                             "System"
#define TEXT_ROMINFO_DEVELOPER                          "Developer"
#define TEXT_ROMINFO_EDITOR                             "Editor"
#define TEXT_ROMINFO_DATE                               "Date"
#define TEXT_ROMINFO_GENRE                              "Genre"
#define TEXT_ROMINFO_PLAYERS                            "Players"
#define TEXT_ROMINFO_RATING                             "Rating"
#define TEXT_ROMINFO_ROTATION                           "Rotation"
#define TEXT_ROMINFO_RESOLUTION                         "Resolution"
#define TEXT_ROMINFO_CLONEOF                            "Clone Of"
#define TEXT_ROMINFO_FILE                               "File"

#define TEXT_UNKOWN                                     "UNKNOWN"
#define TEXT_NONE                                       "NONE"

#define TEXT_BUTTON_LOAD                                "LOAD"
#define TEXT_BUTTON_SAVE                                "SAVE"
#define TEXT_BUTTON_OK                                  "OK"
#define TEXT_BUTTON_CANCEL                              "CANCEL"

#define TEXT_TITTLE_MAIN_OPTIONS                        "MAIN OPTIONS"

// menu
#define TEXT_MENU_MAIN                                  "MAIN"
#define TEXT_MENU_SHOW_FAVORITES                        "SHOW_FAVORITES"
#define TEXT_MENU_SHOW_AVAILABLE                        "SHOW_AVAILABLE"
#define TEXT_MENU_SHOW_CLONES                           "SHOW_CLONES"
#define TEXT_MENU_SHOW_ZIP_NAMES                        "SHOW_ZIP_NAMES"
#define TEXT_MENU_SHOW_ICONS                            "SHOW_ICONS"
#define TEXT_MENU_SCREEN_WIDTH                          "SCREEN_WIDTH"
#define TEXT_MENU_SCREEN_HEIGHT                         "SCREEN_HEIGHT"
#define TEXT_MENU_FULLSCREEN                            "FULLSCREEN"
#define TEXT_MENU_SKIN                                  "SKIN"
#define TEXT_MENU_SKIN_ASPECT                           "SKIN_ASPECT"
#define TEXT_MENU_FONT_SCALING                          "FONT_SCALING"
#define TEXT_MENU_VIDEO_SNAP_DELAY                      "VIDEO_SNAP_DELAY"
#define TEXT_MENU_EMULATION                             "EMULATION"
#define TEXT_MENU_SCALING                               "SCALING"
#define TEXT_MENU_SCALING_MODE                          "SCALING_MODE"
#define TEXT_MENU_FILTER                                "FILTER"
#define TEXT_MENU_WAIT_RENDERING                        "WAIT_RENDERING"
#define TEXT_MENU_SHOW_FPS                              "SHOW_FPS"
#define TEXT_MENU_JOYPAD                                "JOYPAD"
#define TEXT_MENU_JOY_UP                                "JOY_UP"
#define TEXT_MENU_JOY_DOWN                              "JOY_DOWN"
#define TEXT_MENU_JOY_LEFT                              "JOY_LEFT"
#define TEXT_MENU_JOY_RIGHT                             "JOY_RIGHT"
#define TEXT_MENU_JOY_A                                 "JOY_A"
#define TEXT_MENU_JOY_B                                 "JOY_B"
#define TEXT_MENU_JOY_X                                 "JOY_X"
#define TEXT_MENU_JOY_Y                                 "JOY_Y"
#define TEXT_MENU_JOY_LT                                "JOY_LT"
#define TEXT_MENU_JOY_RT                                "JOY_RT"
#define TEXT_MENU_JOY_LB                                "JOY_LB"
#define TEXT_MENU_JOY_RB                                "JOY_RB"
#define TEXT_MENU_JOY_SELECT                            "JOY_SELECT"
#define TEXT_MENU_JOY_START                             "JOY_START"
#define TEXT_MENU_JOY_MENU1                             "JOY_MENU1"
#define TEXT_MENU_JOY_MENU2                             "JOY_MENU2"
#define TEXT_MENU_JOY_AXIS_LX                           "JOY_AXIS_LX"
#define TEXT_MENU_JOY_AXIS_LY                           "JOY_AXIS_LY"
#define TEXT_MENU_JOY_AXIS_RX                           "JOY_AXIS_RX"
#define TEXT_MENU_JOY_AXIS_RY                           "JOY_AXIS_RY"
#define TEXT_MENU_JOY_DEADZONE                          "JOY_DEADZONE"
#define TEXT_MENU_KEYBOARD                              "KEYBOARD"
#define TEXT_MENU_KEY_UP                                "KEY_UP"
#define TEXT_MENU_KEY_DOWN                              "KEY_DOWN"
#define TEXT_MENU_KEY_LEFT                              "KEY_LEFT"
#define TEXT_MENU_KEY_RIGHT                             "KEY_RIGHT"
#define TEXT_MENU_KEY_A                                 "KEY_A"
#define TEXT_MENU_KEY_B                                 "KEY_B"
#define TEXT_MENU_KEY_X                                 "KEY_X"
#define TEXT_MENU_KEY_Y                                 "KEY_Y"
#define TEXT_MENU_KEY_LT                                "KEY_LT"
#define TEXT_MENU_KEY_RT                                "KEY_RT"
#define TEXT_MENU_KEY_LB                                "KEY_LB"
#define TEXT_MENU_KEY_RB                                "KEY_RB"
#define TEXT_MENU_KEY_SELECT                            "KEY_SELECT"
#define TEXT_MENU_KEY_START                             "KEY_START"
#define TEXT_MENU_KEY_MENU1                             "KEY_MENU1"
#define TEXT_MENU_KEY_MENU2                             "KEY_MENU2"

#define TEXT_MENU_EFFECT                                "EFFECT"
#define TEXT_MENU_FORCE_60HZ                            "FORCE_60HZ"
#define TEXT_MENU_AUDIO_FREQUENCY                       "AUDIO_FREQUENCY"
#define TEXT_MENU_AUDIO_INTERPOLATION                   "AUDIO_INTERPOLATION"
#define TEXT_MENU_AUDIO_FM_INTERPOLATION                "AUDIO_FM_INTERPOLATION"
#define TEXT_MENU_ROTATION                              "ROTATION"
#define TEXT_MENU_NEOBIOS                               "NEOBIOS"
#define TEXT_MENU_FRAMESKIP                             "FRAMESKIP"

#define TEXT_MENU_AUDIO_SYNC                            "AUDIO_SYNC"
#define TEXT_MENU_CHEATS                                "CHEATS"
#define TEXT_MENU_BLOCK_INVALID_VRAM                    "BLOCK_INVALID_VRAM"
#define TEXT_MENU_TRANSPARENCY                          "TRANSPARENCY"
#define TEXT_MENU_DISPLAY_MESSAGES                      "DISPLAY_MESSAGES"
#define TEXT_MENU_TURBO_MODE                            "TURBO_MODE"
#define TEXT_MENU_TURBO_FRAMESKIP                       "TURBO_FRAMESKIP"

#define TEXT_MENU_FILTER_SYSTEM                         "FILTER_SYSTEM"
#define TEXT_MENU_FILTER_GENRE                          "FILTER_GENRE"
#define TEXT_MENU_FILTER_DATE                           "FILTER_DATE"
#define TEXT_MENU_FILTER_EDITOR                         "FILTER_EDITOR"
#define TEXT_MENU_FILTER_DEVELOPER                      "FILTER_DEVELOPER"
#define TEXT_MENU_FILTER_PLAYERS                        "FILTER_PLAYERS"
#define TEXT_MENU_FILTER_RATING                         "FILTER_RATING"
#define TEXT_MENU_FILTER_ROTATION                       "FILTER_ROTATION"
#define TEXT_MENU_FILTER_RESOLUTION                     "FILTER_RESOLUTION"

// misc
#define TEXT_SLOT                                       "SLOT"
#define TEXT_NO_SAVE                                    "NO SAVE"

// message
#define TEXT_MSG_TITTLE_ERROR                           "ERROR"
#define TEXT_MSG_TITTLE_WARNING                         "WARNING"

#define TEXT_MSG_PLEASE_WAIT                            "Please wait..."
#define TEXT_MSG_GAMES_SEARCH                           "Games: %li / %li"

#define TEXT_MSG_PRESS_FIRE2_TO_CANCEL                  "PRESS FIRE2 TO CANCEL"
#define TEXT_MSG_NEW_INPUT                              "NEW INPUT"
#define TEXT_MSG_PRESS_A_BUTTON                         "PRESS A BUTTON"

#define TEXT_MSG_TITTLE_FAVORITES                       "FAVORITES"
#define TEXT_MSG_ADD_FAVORITES                          "Add to favorites ?"
#define TEXT_MSG_REMOVE_FAVORITES                       "Remove from favorites ?"

#define TEXT_MSG_DISPLAY_INFO                           "GAME: %ix%i - RATIO: %.2f | OUTPUT: %ix%i - RATIO: %.2f - SCALING: %.2fx%.2f"
#define TEXT_MSG_TRY_TO_KEEP_INTEGER_SCALING            "TRY TO KEEP INTEGER SCALING IF ASPECT RATIO IS NOT TOO DIVERGENT"
#define TEXT_MSG_KEEP_ASPECT_RATIO                      "KEEP GAME ASPECT RATIO - SOME SHADERS MAY NOT RENDER CORRECTLY"
#define TEXT_MSG_FORCE_INTEGER_SCALING                  "FORCE INTEGER SCALING - ASPECT RATIO MAY BE WRONG BUT SHADERS WILL RENDER CORRECTLY"

#define TEXT_MSG_ERROR_LOADING                          "Error loading %s for %s.\nEmulation will likely have problems."

#define TEXT_MSG_DRIVER_INIT_FAILED                     "DRIVER INIT FAILED"

#define TEXT_MSG_UNIBIOS_DONT_SUPPORT_M68K_ASM_CORE     "UNIBIOS DOESNT SUPPORT THE M68K ASM CORE\nCYCLONE ASM CORE DISABLED"
#define TEXT_MSG_ROM_CRYPTED                            "ROM IS CRYPTED, USE DECRYPTED ROM (CLONE)\nTO ENABLE CYCLONE ASM CORE (FASTER)"
#define TEXT_MSG_NOT_SUPPORT_M68K_ASM_CODE              "THIS GAME DOES NOT SUPPORT THE M68K ASM CORE\nCYCLONE ASM CORE DISABLED"

#define TEXT_MSG_NEED_APP_RESTART                       "YOU NEED TO RESTART THE APPLICATION AFTER CHANGING THIS OPTION"

#define TEXT_MSG_PRESS_MENU1_2_FOR_INGAME_MENU          "TIPS: PRESS MENU1 + MENU2 BUTTONS FOR IN GAME MENU..."
#define TEXT_MSG_PRESS_BUTTON2_FOR_DIAG_MENU            "TIPS: PRESS START BUTTON 2 SECONDS FOR DIAG MENU..."
#define TEXT_MSG_PRESS_COIN_BUTTON_TO_RESET             "TIPS: PRESS COIN BUTTON 2 SECONDS TO RESET CURRENT GAME..."

#define TEXT_MSG_PNES_INVALID_FILE                      "INVALID FILE"

#define TEXT_MSG_PSNES_INVALID_ROM                      "INVALID ROM"

#define TEXT_MSG_PGEN_MISSING_MEGA_CD_BIOS              "MISSING MEGA-CD BIOS DETECTED, EMULATION WILL LIKELY NOT WORK..."
#define TEXT_MSG_PGEN_INVALID_FILE_OR_MISSING_BIOS      "INVALID FILE OR MISSING BIOS..."

#define TEXT_MSG_PFBNEO_NEED_EMLATION_RESTART           "YOU NEED TO RESTART EMULATION AFTER CHANGING THIS OPTION"

#else

// main framework
#define TEXT_NAVIGATION                                 "导航"
#define TEXT_RUN                                        "运行"
#define TEXT_TOOGLE_FAVORITE                            "添加/移出收藏"
#define TEXT_FAVORITE                                   "收藏夹"
#define TEXT_SWITCH_SYSTEM                              "切换机种"
#define TEXT_MAIN_MENU                                  "全局菜单"
#define TEXT_ROM_MENU                                   "ROM菜单"

#define TEXT_ROMINFO_DELIMITER                          ": "
#define TEXT_ROMINFO_SYSTEM                             "机种"
#define TEXT_ROMINFO_DEVELOPER                          "开发商"
#define TEXT_ROMINFO_EDITOR                             "发行商"
#define TEXT_ROMINFO_DATE                               "发售年份"
#define TEXT_ROMINFO_GENRE                              "类型"
#define TEXT_ROMINFO_PLAYERS                            "游玩人数"
#define TEXT_ROMINFO_RATING                             "评分"
#define TEXT_ROMINFO_ROTATION                           "屏幕旋转角度"
#define TEXT_ROMINFO_RESOLUTION                         "分辨率"
#define TEXT_ROMINFO_CLONEOF                            "原版"
#define TEXT_ROMINFO_FILE                               "文件名"

#define TEXT_UNKOWN                                     "未知"
#define TEXT_NONE                                       "无"

#define TEXT_BUTTON_LOAD                                "读取"
#define TEXT_BUTTON_SAVE                                "保存"
#define TEXT_BUTTON_OK                                  "确定"
#define TEXT_BUTTON_CANCEL                              "取消"

#define TEXT_TITTLE_MAIN_OPTIONS                        "全局菜单"

// menu
#define TEXT_MENU_MAIN                                  "通用"
#define TEXT_MENU_SHOW_FAVORITES                        "显示收藏夹"
#define TEXT_MENU_SHOW_AVAILABLE                        "只显示已有内容"
#define TEXT_MENU_SHOW_CLONES                           "显示所有版本"
#define TEXT_MENU_SHOW_ZIP_NAMES                        "显示文件名"
#define TEXT_MENU_SHOW_ICONS                            "显示图标"
#define TEXT_MENU_SCREEN_WIDTH                          "屏幕-宽度"
#define TEXT_MENU_SCREEN_HEIGHT                         "屏幕-高度"
#define TEXT_MENU_FULLSCREEN                            "全屏"
#define TEXT_MENU_SKIN                                  "皮肤"
#define TEXT_MENU_SKIN_ASPECT                           "皮肤长宽比"
#define TEXT_MENU_FONT_SCALING                          "字体大小"
#define TEXT_MENU_VIDEO_SNAP_DELAY                      "视频采集延迟"
#define TEXT_MENU_EMULATION                             "模拟"
#define TEXT_MENU_SCALING                               "缩放比例"
#define TEXT_MENU_SCALING_MODE                          "缩放模式"
#define TEXT_MENU_FILTER                                "纹理过滤"
#define TEXT_MENU_WAIT_RENDERING                        "等待渲染"
#define TEXT_MENU_SHOW_FPS                              "显示帧率"
#define TEXT_MENU_JOYPAD                                "手柄设置"
#define TEXT_MENU_JOY_UP                                "手柄 ↑"
#define TEXT_MENU_JOY_DOWN                              "手柄 ↓"
#define TEXT_MENU_JOY_LEFT                              "手柄 ←"
#define TEXT_MENU_JOY_RIGHT                             "手柄 →"
#define TEXT_MENU_JOY_A                                 "手柄 A"
#define TEXT_MENU_JOY_B                                 "手柄 B"
#define TEXT_MENU_JOY_X                                 "手柄 X"
#define TEXT_MENU_JOY_Y                                 "手柄 Y"
#define TEXT_MENU_JOY_LT                                "手柄 LT"
#define TEXT_MENU_JOY_RT                                "手柄 RT"
#define TEXT_MENU_JOY_LB                                "手柄 LB"
#define TEXT_MENU_JOY_RB                                "手柄 RB"
#define TEXT_MENU_JOY_SELECT                            "手柄 SELECT"
#define TEXT_MENU_JOY_START                             "手柄 START"
#define TEXT_MENU_JOY_MENU1                             "手柄 MENU1"
#define TEXT_MENU_JOY_MENU2                             "手柄 MENU2"
#define TEXT_MENU_JOY_AXIS_LX                           "手柄 左摇杆x轴"
#define TEXT_MENU_JOY_AXIS_LY                           "手柄 左摇杆y轴"
#define TEXT_MENU_JOY_AXIS_RX                           "手柄 右摇杆x轴"
#define TEXT_MENU_JOY_AXIS_RY                           "手柄 右摇杆y轴"
#define TEXT_MENU_JOY_DEADZONE                          "手柄 摇杆死区"
#define TEXT_MENU_KEYBOARD                              "键盘设置"
#define TEXT_MENU_KEY_UP                                "键盘 ↑"
#define TEXT_MENU_KEY_DOWN                              "键盘 ↓"
#define TEXT_MENU_KEY_LEFT                              "键盘 ←"
#define TEXT_MENU_KEY_RIGHT                             "键盘 →"
#define TEXT_MENU_KEY_A                                 "键盘 A"
#define TEXT_MENU_KEY_B                                 "键盘 B"
#define TEXT_MENU_KEY_X                                 "键盘 X"
#define TEXT_MENU_KEY_Y                                 "键盘 Y"
#define TEXT_MENU_KEY_LT                                "键盘 LT"
#define TEXT_MENU_KEY_RT                                "键盘 RT"
#define TEXT_MENU_KEY_LB                                "键盘 LB"
#define TEXT_MENU_KEY_RB                                "键盘 RB"
#define TEXT_MENU_KEY_SELECT                            "键盘 SELECT"
#define TEXT_MENU_KEY_START                             "键盘 START"
#define TEXT_MENU_KEY_MENU1                             "键盘 MENU1"
#define TEXT_MENU_KEY_MENU2                             "键盘 MENU2"

#define TEXT_MENU_EFFECT                                "渲染效果"
#define TEXT_MENU_FORCE_60HZ                            "强制60帧"
#define TEXT_MENU_AUDIO_FREQUENCY                       "声音频率"
#define TEXT_MENU_AUDIO_INTERPOLATION                   "声音插值"
#define TEXT_MENU_AUDIO_FM_INTERPOLATION                "声音FM插值"
#define TEXT_MENU_ROTATION                              "旋转屏幕"
#define TEXT_MENU_NEOBIOS                               "NEOBIOS"
#define TEXT_MENU_FRAMESKIP                             "跳帧"

#define TEXT_MENU_AUDIO_SYNC                            "声音同步"
#define TEXT_MENU_CHEATS                                "作弊"
#define TEXT_MENU_BLOCK_INVALID_VRAM                    "阻止非法显存块"
#define TEXT_MENU_TRANSPARENCY                          "透明度"
#define TEXT_MENU_DISPLAY_MESSAGES                      "显示提示信息"
#define TEXT_MENU_TURBO_MODE                            "TURBO模式"
#define TEXT_MENU_TURBO_FRAMESKIP                       "TURBO跳帧"

// OLIVER TODO
#define TEXT_MENU_FILTER_SYSTEM                         "筛选机种"
#define TEXT_MENU_FILTER_GENRE                          "筛选类型"
#define TEXT_MENU_FILTER_DATE                           "筛选发售年份"
#define TEXT_MENU_FILTER_EDITOR                         "筛选发行商"
#define TEXT_MENU_FILTER_DEVELOPER                      "筛选开发商"
#define TEXT_MENU_FILTER_PLAYERS                        "筛选游戏人数"
#define TEXT_MENU_FILTER_RATING                         "筛选评分"
#define TEXT_MENU_FILTER_ROTATION                       "筛选屏幕旋转角度"
#define TEXT_MENU_FILTER_RESOLUTION                     "筛选分辨率"

// misc
#define TEXT_SLOT                                       "存档"
#define TEXT_NO_SAVE                                    "空"

// message
#define TEXT_MSG_TITTLE_ERROR                           "出错了..."
#define TEXT_MSG_TITTLE_WARNING                         "警告"

#define TEXT_MSG_PLEASE_WAIT                            "请稍等..."
#define TEXT_MSG_GAMES_SEARCH                           "正在扫描 : %li / %li"

#define TEXT_MSG_PRESS_FIRE2_TO_CANCEL                  "按 FIRE2 键可取消"
#define TEXT_MSG_NEW_INPUT                              "新输入"
#define TEXT_MSG_PRESS_A_BUTTON                         "请按下一个键"

#define TEXT_MSG_TITTLE_FAVORITES                       "收藏夹"
#define TEXT_MSG_ADD_FAVORITES                          "要加入收藏夹吗?"
#define TEXT_MSG_REMOVE_FAVORITES                       "要移出收藏夹吗?"

#define TEXT_MSG_DISPLAY_INFO                           "原生: %ix%i - 比例: %.2f | 输出: %ix%i - 比例: %.2f - 缩放比例: %.2fx%.2f"
#define TEXT_MSG_TRY_TO_KEEP_INTEGER_SCALING            "尽量保持整数缩放比例,如果长宽比差别不大"
#define TEXT_MSG_KEEP_ASPECT_RATIO                      "保持游戏的长宽比 - 一些着色器可能无法正确渲染"
#define TEXT_MSG_FORCE_INTEGER_SCALING                  "强制使用整数缩放比例 - 长宽比可能不正确,但着色器能正确渲染"

#define TEXT_MSG_ERROR_LOADING                          "加载ROM %s (驱动:%s) 出错\n模拟可能会有问题"
#define TEXT_MSG_DRIVER_INIT_FAILED                     "驱动初始化失败"

#define TEXT_MSG_UNIBIOS_DONT_SUPPORT_M68K_ASM_CORE     "UNIBIOS不支持M68000的汇编内核\ncyclone 68000汇编内核被禁用"
#define TEXT_MSG_ROM_CRYPTED                            "ROM被加密了,请使用解密的ROM版本\n来启用cyclone 68000汇编内核(速度更快)"
#define TEXT_MSG_NOT_SUPPORT_M68K_ASM_CODE              "这个游戏不支持M68000的汇编内核\cyclone 68000汇编内核被禁用"

#define TEXT_MSG_NEED_APP_RESTART                       "你需要重启程序以使修改生效"

#define TEXT_MSG_PRESS_MENU1_2_FOR_INGAME_MENU          "提示: 同时按下MENU1键和MENU2键可以在游戏中打开菜单..."
#define TEXT_MSG_PRESS_BUTTON2_FOR_DIAG_MENU            "提示: 按住START键2秒可以打开对话菜单..."
#define TEXT_MSG_PRESS_COIN_BUTTON_TO_RESET             "提示: 按住投币键2秒可以重置当前游戏..."

#define TEXT_MSG_PNES_INVALID_FILE                      "文件非法"

#define TEXT_MSG_PSNES_INVALID_ROM                      "ROM文件非法"

#define TEXT_MSG_PGEN_MISSING_MEGA_CD_BIOS              "没有找到MEGA-CD的BIOS文件,模拟可能无法成功..."
#define TEXT_MSG_PGEN_INVALID_FILE_OR_MISSING_BIOS      "ROM文件非法或找不到BIOS文件..."

#define TEXT_MSG_PFBNEO_NEED_EMLATION_RESTART           "你需要重新开始模拟以使修改生效"

#endif

#endif